var searchData=
[
  ['deprecated_20list_39',['Deprecated List',['../deprecated.html',1,'']]],
  ['desktophandler_40',['DesktopHandler',['../classit_1_1unical_1_1mat_1_1embasp_1_1platforms_1_1desktop_1_1DesktopHandler.html',1,'it::unical::mat::embasp::platforms::desktop']]],
  ['desktopservice_41',['DesktopService',['../classit_1_1unical_1_1mat_1_1embasp_1_1platforms_1_1desktop_1_1DesktopService.html',1,'it::unical::mat::embasp::platforms::desktop']]],
  ['dlv2androidreasoner_42',['DLV2AndroidReasoner',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv2_1_1android_1_1DLV2AndroidReasoner.html',1,'it::unical::mat::embasp::specializations::dlv2::android']]],
  ['dlv2androidservice_43',['DLV2AndroidService',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv2_1_1android_1_1DLV2AndroidService.html',1,'it::unical::mat::embasp::specializations::dlv2::android']]],
  ['dlv2answersets_44',['DLV2AnswerSets',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv2_1_1DLV2AnswerSets.html',1,'it::unical::mat::embasp::specializations::dlv2']]],
  ['dlv2desktopservice_45',['DLV2DesktopService',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv2_1_1desktop_1_1DLV2DesktopService.html',1,'it::unical::mat::embasp::specializations::dlv2::desktop']]],
  ['dlv2lexer_46',['DLV2Lexer',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv2_1_1DLV2Lexer.html',1,'it::unical::mat::parsers::asp::dlv2']]],
  ['dlv2parser_47',['DLV2Parser',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv2_1_1DLV2Parser.html',1,'it::unical::mat::parsers::asp::dlv2']]],
  ['dlv2parserbasevisitor_48',['DLV2ParserBaseVisitor',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv2_1_1DLV2ParserBaseVisitor.html',1,'it::unical::mat::parsers::asp::dlv2']]],
  ['dlv2parserbasevisitor_3c_20void_20_3e_49',['DLV2ParserBaseVisitor&lt; Void &gt;',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv2_1_1DLV2ParserBaseVisitor.html',1,'it::unical::mat::parsers::asp::dlv2']]],
  ['dlv2parserbasevisitorimplementation_50',['DLV2ParserBaseVisitorImplementation',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv2_1_1DLV2ParserBaseVisitorImplementation.html',1,'it::unical::mat::parsers::asp::dlv2']]],
  ['dlv2parservisitor_51',['DLV2ParserVisitor',['../interfaceit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv2_1_1DLV2ParserVisitor.html',1,'it::unical::mat::parsers::asp::dlv2']]],
  ['dlvandroidreasoner_52',['DLVAndroidReasoner',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1android_1_1DLVAndroidReasoner.html',1,'it::unical::mat::embasp::specializations::dlv::android']]],
  ['dlvandroidservice_53',['DLVAndroidService',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1android_1_1DLVAndroidService.html',1,'it::unical::mat::embasp::specializations::dlv::android']]],
  ['dlvanswersets_54',['DLVAnswerSets',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1DLVAnswerSets.html',1,'it.unical.mat.embasp.specializations.dlv.DLVAnswerSets'],['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1DLVAnswerSets.html#aba3f3268a09a033fa18b5241f95f43f8',1,'it.unical.mat.embasp.specializations.dlv.DLVAnswerSets.DLVAnswerSets()']]],
  ['dlvdesktopservice_55',['DLVDesktopService',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1desktop_1_1DLVDesktopService.html',1,'it::unical::mat::embasp::specializations::dlv::desktop']]],
  ['dlvdesktopservicetest_56',['DLVDesktopServiceTest',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1DLVDesktopServiceTest.html',1,'it::unical::mat::embasp::specializations::dlv']]],
  ['dlvfilteroption_57',['DLVFilterOption',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlv_1_1DLVFilterOption.html',1,'it::unical::mat::embasp::specializations::dlv']]],
  ['dlvhexanswersets_58',['DLVHEXAnswerSets',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlvhex_1_1DLVHEXAnswerSets.html',1,'it::unical::mat::embasp::specializations::dlvhex']]],
  ['dlvhexdesktopservice_59',['DLVHEXDesktopService',['../classit_1_1unical_1_1mat_1_1embasp_1_1specializations_1_1dlvhex_1_1desktop_1_1DLVHEXDesktopService.html',1,'it::unical::mat::embasp::specializations::dlvhex::desktop']]],
  ['dlvhexlexer_60',['DLVHEXLexer',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlvhex_1_1DLVHEXLexer.html',1,'it::unical::mat::parsers::asp::dlvhex']]],
  ['dlvhexparser_61',['DLVHEXParser',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlvhex_1_1DLVHEXParser.html',1,'it::unical::mat::parsers::asp::dlvhex']]],
  ['dlvhexparserbasevisitor_62',['DLVHEXParserBaseVisitor',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlvhex_1_1DLVHEXParserBaseVisitor.html',1,'it::unical::mat::parsers::asp::dlvhex']]],
  ['dlvhexparserbasevisitor_3c_20void_20_3e_63',['DLVHEXParserBaseVisitor&lt; Void &gt;',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlvhex_1_1DLVHEXParserBaseVisitor.html',1,'it::unical::mat::parsers::asp::dlvhex']]],
  ['dlvhexparserbasevisitorimplementation_64',['DLVHEXParserBaseVisitorImplementation',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlvhex_1_1DLVHEXParserBaseVisitorImplementation.html',1,'it::unical::mat::parsers::asp::dlvhex']]],
  ['dlvhexparservisitor_65',['DLVHEXParserVisitor',['../interfaceit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlvhex_1_1DLVHEXParserVisitor.html',1,'it::unical::mat::parsers::asp::dlvhex']]],
  ['dlvlexer_66',['DLVLexer',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv_1_1DLVLexer.html',1,'it::unical::mat::parsers::asp::dlv']]],
  ['dlvparser_67',['DLVParser',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv_1_1DLVParser.html',1,'it::unical::mat::parsers::asp::dlv']]],
  ['dlvparserbasevisitor_68',['DLVParserBaseVisitor',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv_1_1DLVParserBaseVisitor.html',1,'it::unical::mat::parsers::asp::dlv']]],
  ['dlvparserbasevisitor_3c_20void_20_3e_69',['DLVParserBaseVisitor&lt; Void &gt;',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv_1_1DLVParserBaseVisitor.html',1,'it::unical::mat::parsers::asp::dlv']]],
  ['dlvparserbasevisitorimplementation_70',['DLVParserBaseVisitorImplementation',['../classit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv_1_1DLVParserBaseVisitorImplementation.html',1,'it::unical::mat::parsers::asp::dlv']]],
  ['dlvparservisitor_71',['DLVParserVisitor',['../interfaceit_1_1unical_1_1mat_1_1parsers_1_1asp_1_1dlv_1_1DLVParserVisitor.html',1,'it::unical::mat::parsers::asp::dlv']]]
];
